import Head from 'next/head';
import { SITE_NAME } from '../../constant/site';
import { IChildrenProps } from '../interfaces/children-props.interface';

export interface IPageWrapper extends IChildrenProps {
  title?: string;
}

const PageWrapper: React.FC<IPageWrapper> = ({
  title = SITE_NAME,
  children,
}) => {
  return (
    <>
      <Head>
        <title>{`${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
};

export default PageWrapper;
